//! Cargo-compatible command-line parsing and normalization.

use std::collections::BTreeSet;
use std::ffi::{OsStr, OsString};
use std::path::{Path, PathBuf};

use clap::{ArgAction, Parser};

use crate::model::{Root, RootFilePolicy, Selection};

/// Parsed command-line options before filesystem normalization.
#[derive(Debug, Parser)]
#[command(
    name = "cargo-sloc",
    version,
    about = "Source line counts for supported files beneath a directory",
    long_about = "Count supported, non-ignored source beneath PATH. By default, every eligible Package, all features, all package targets, and supported Root files are included. Reachable package Rust receives configuration-aware accounting; other recognized files are retained under their Package or the Root scope.",
    after_help = "Examples:\n  cargo sloc\n  cargo sloc ../workspace\n  cargo sloc --features serde,simd\n  cargo sloc --no-default-features --features serde\n  cargo sloc --root-files exclude\n  cargo sloc --json"
)]
struct Arguments {
    /// Root directory to search for supported source and Cargo projects.
    #[arg(value_name = "PATH", default_value = ".")]
    root: PathBuf,

    /// Select packages using Cargo package specifications.
    #[arg(short = 'p', long = "package", value_name = "SPEC", action = ArgAction::Append)]
    packages: Vec<String>,

    /// Select every eligible workspace package beneath the Root.
    #[arg(long)]
    workspace: bool,

    /// Exclude a package from workspace-wide selection.
    #[arg(long, value_name = "SPEC", requires = "workspace", action = ArgAction::Append)]
    exclude: Vec<String>,

    /// Include or exclude files whose final report owner is the Root.
    #[arg(long, value_enum, default_value_t = RootFilePolicy::Include)]
    root_files: RootFilePolicy,

    /// Enable a comma- or space-separated Cargo feature list.
    #[arg(short = 'F', long, value_name = "FEATURES", action = ArgAction::Append)]
    features: Vec<String>,

    /// Enable every feature.
    #[arg(long)]
    all_features: bool,

    /// Disable default features unless enabled by another selection.
    #[arg(long)]
    no_default_features: bool,

    /// Select a compilation target; may be repeated.
    #[arg(long, value_name = "TARGET", action = ArgAction::Append)]
    target: Vec<String>,

    /// Select the library target.
    #[arg(long)]
    lib: bool,

    /// Select a named binary target.
    #[arg(long, value_name = "NAME", action = ArgAction::Append)]
    bin: Vec<String>,

    /// Select all binary targets.
    #[arg(long)]
    bins: bool,

    /// Select a named example target.
    #[arg(long, value_name = "NAME", action = ArgAction::Append)]
    example: Vec<String>,

    /// Select all example targets.
    #[arg(long)]
    examples: bool,

    /// Select a named integration-test target.
    #[arg(long, value_name = "NAME", action = ArgAction::Append)]
    test: Vec<String>,

    /// Select all test-enabled targets.
    #[arg(long)]
    tests: bool,

    /// Select a named benchmark target.
    #[arg(long, value_name = "NAME", action = ArgAction::Append)]
    bench: Vec<String>,

    /// Select all benchmark-enabled targets.
    #[arg(long)]
    benches: bool,

    /// Select all cargo-sloc package targets and contexts.
    #[arg(long)]
    all_targets: bool,

    /// Exclude a target or target kind after inclusion.
    #[arg(long, value_name = "KIND[:NAME]", action = ArgAction::Append)]
    exclude_target: Vec<String>,

    /// Emit schema-version 3 JSON instead of the terminal table.
    #[arg(long)]
    json: bool,
}

/// A parsed request or a fully rendered clap response.
pub enum ParseOutcome {
    /// Continue normal command execution.
    Selection(Selection),
    /// Help, version, or usage-error output generated by clap.
    EarlyExit {
        /// Complete buffered stdout bytes.
        stdout: Vec<u8>,
        /// Complete buffered stderr bytes.
        stderr: Vec<u8>,
        /// Process exit status.
        exit_code: u8,
    },
}

/// Parses direct or Cargo external-subcommand arguments.
pub fn parse<I, T>(
    arguments: I,
    current_directory: &Path,
) -> Result<ParseOutcome, crate::error::AppError>
where
    I: IntoIterator<Item = T>,
    T: Into<OsString>,
{
    let mut arguments: Vec<OsString> = arguments.into_iter().map(Into::into).collect();
    if arguments
        .first()
        .is_some_and(|argument| argument == OsStr::new("sloc"))
    {
        arguments.remove(0);
    }

    let argv = std::iter::once(OsString::from("cargo-sloc")).chain(arguments);
    let parsed = match Arguments::try_parse_from(argv) {
        Ok(parsed) => parsed,
        Err(error) => {
            let exit_code = if error.use_stderr() { 2 } else { 0 };
            let rendered = error.render().to_string().into_bytes();
            return Ok(ParseOutcome::EarlyExit {
                stdout: if exit_code == 0 {
                    rendered.clone()
                } else {
                    Vec::new()
                },
                stderr: if exit_code == 0 { Vec::new() } else { rendered },
                exit_code,
            });
        }
    };

    let features_requested = !parsed.features.is_empty();
    let features = split_features(&parsed.features);
    let target_includes = target_includes(&parsed);
    let target_excludes = parsed
        .exclude_target
        .iter()
        .map(|selector| canonical_exclusion(selector))
        .collect::<Result<_, _>>()
        .map_err(clap_usage_error)?;

    Ok(ParseOutcome::Selection(Selection {
        root: Root::resolve(&parsed.root, current_directory)?,
        package_selectors: parsed.packages.into_iter().collect(),
        workspace: parsed.workspace,
        package_exclude_selectors: parsed.exclude.into_iter().collect(),
        root_files: parsed.root_files,
        all_features: parsed.all_features || (!features_requested && !parsed.no_default_features),
        no_default_features: parsed.no_default_features,
        features,
        requested_targets: parsed.target.into_iter().collect(),
        target_includes,
        target_excludes,
        json: parsed.json,
    }))
}

fn split_features(values: &[String]) -> BTreeSet<String> {
    values
        .iter()
        .flat_map(|value| value.split([',', ' ', '\t', '\n', '\r']))
        .filter(|feature| !feature.is_empty())
        .map(str::to_owned)
        .collect()
}

fn target_includes(arguments: &Arguments) -> BTreeSet<String> {
    let mut includes = BTreeSet::new();
    if arguments.lib {
        includes.insert("lib".to_owned());
    }
    if arguments.bins {
        includes.insert("bins".to_owned());
    }
    includes.extend(arguments.bin.iter().map(|name| format!("bin:{name}")));
    if arguments.examples {
        includes.insert("examples".to_owned());
    }
    includes.extend(
        arguments
            .example
            .iter()
            .map(|name| format!("example:{name}")),
    );
    if arguments.tests {
        includes.insert("tests".to_owned());
    }
    includes.extend(arguments.test.iter().map(|name| format!("test:{name}")));
    if arguments.benches {
        includes.insert("benches".to_owned());
    }
    includes.extend(arguments.bench.iter().map(|name| format!("bench:{name}")));
    if arguments.all_targets || includes.is_empty() {
        includes.insert("all-targets".to_owned());
    }
    includes
}

fn canonical_exclusion(selector: &str) -> Result<String, String> {
    let (kind, name) = selector
        .split_once(':')
        .map_or((selector, None), |(kind, name)| (kind, Some(name)));
    let supports_name = matches!(kind, "lib" | "bin" | "example" | "test" | "bench");
    if !matches!(
        kind,
        "lib" | "bin" | "example" | "test" | "bench" | "build-script"
    ) {
        return Err(format!("invalid target-exclusion kind `{kind}`"));
    }
    if name.is_some_and(str::is_empty) {
        return Err(format!(
            "target-exclusion selector `{selector}` has an empty name"
        ));
    }
    if name.is_some() && !supports_name {
        return Err("`build-script` does not accept a target name".to_owned());
    }
    if name.is_some_and(|name| name.contains(':')) {
        return Err(format!(
            "target-exclusion selector `{selector}` has too many separators"
        ));
    }
    Ok(selector.to_owned())
}

fn clap_usage_error(message: String) -> crate::error::AppError {
    crate::error::AppError::Usage(message)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn feature_lists_are_flattened_and_deduplicated() {
        assert_eq!(
            split_features(&["serde,simd".to_owned(), "simd logging".to_owned()]),
            BTreeSet::from(["logging".to_owned(), "serde".to_owned(), "simd".to_owned()])
        );
    }

    #[test]
    fn target_exclusions_reject_invalid_forms() {
        assert!(canonical_exclusion("build-script:named").is_err());
        assert!(canonical_exclusion("unknown").is_err());
        assert!(canonical_exclusion("bin:").is_err());
        assert_eq!(canonical_exclusion("test:api").unwrap(), "test:api");
    }
}
